//
// Created by illfate on 12/5/20.
//

#ifndef FAMILY_BUDGET_MANAGER_FINANCIALEVENT_H
#define FAMILY_BUDGET_MANAGER_FINANCIALEVENT_H


class FinancialEvent {

};


#endif //FAMILY_BUDGET_MANAGER_FINANCIALEVENT_H
