//
// Created by illfate on 12/12/20.
//

#ifndef FAMILY_BUDGET_MANAGER_OPTIMIZATIONADVICE_H
#define FAMILY_BUDGET_MANAGER_OPTIMIZATIONADVICE_H


class OptimizationAdvice {

};


#endif //FAMILY_BUDGET_MANAGER_OPTIMIZATIONADVICE_H
